services:
  koleksi-resep-api:
    build:
      context: .
    container_name: koleksi-resep-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    command: sh -c "npm run migrate up && npm run start"
    networks:
      - global

networks:
  global:
    external: true
    name: nilabiru-data-hub